version: '3'

volumes:
  mongo_data:
    external: true

services:
  mongo:
    image: mongo
    volumes:
    - mongo_data:/data/db
    ports:
    - 27037:27017

  mongo_express:
    image: mongo-express
    ports:
    - 8193:8081
    links:
    - mongo
    depends_on:
    - mongo
