[[constraint]]
  name = "github.com/globalsign/mgo"
  branch = "master"

[[constraint]]
  name = "github.com/go-ozzo/ozzo-validation"
  version = "3.4.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"

[[constraint]]
  name = "github.com/hybridgroup/mjpeg"
  branch = "master"

[[constraint]]
  name = "github.com/ic2hrmk/go-event"
  branch = "master"

[[constraint]]
  name = "gocv.io/x/gocv"
  version = "0.12.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.0.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "=1.3.0"

[prune]
  go-tests = true
  unused-packages = true
