version: '3.1'

volumes:
  gis_mongo_data:
    external: true

services:
  mongo:
    image: mongo
    volumes:
      - gis_mongo_data:/data/db
    ports:
      - 27017:27017

  mongo_express:
    image: mongo-express
    ports:
      - 8193:8081
    links:
      - mongo
    depends_on:
      - mongo

  route:
    image: golang:latest
    volumes:
    - .:${GOPATH}/src/trans/
    working_dir: ${GOPATH}/src/trans/service
    command: go run ./gateway/main.go --kind=route
    ports:
    - 8081:8080
    restart: always
    networks:
    - web