version: '3.1'

volumes:
  server_mongo_data:
    external: true

services:
  mongo:
    image: mongo
    logging:
      driver: none
    volumes:
      - server_mongo_data:/data/db
    ports:
      - 27017:27017

  mongo_express:
    image: mongo-express
    ports:
      - 7017:8081
    links:
      - mongo
    logging:
      driver: none
    depends_on:
      - mongo

#  route:
#    image: golang:latest
#    volumes:
#    - .:/go/src/trans/server/
#    working_dir: /go/src/trans/server/
#    command: go run ./entry/main.go --kind=route --env=.env
#    ports:
#    - 8081:8080
#    restart: always
