[[constraint]]
  name = "github.com/joho/godotenv"
  version = "=1.3.0"

[[constraint]]
  name = "github.com/go-resty/resty"
  version = "=1.10.2"

[[constraint]]
  name = "github.com/globalsign/mgo"
  branch = "master"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-ozzo/ozzo-validation"
  version = "3.4.0"