[[constraint]]
  name = "github.com/joho/godotenv"
  version = "=1.3.0"

[[constraint]]
  name = "github.com/go-resty/resty"
  version = "=1.10.2"

[[constraint]]
  name = "github.com/globalsign/mgo"
  branch = "master"
